### ISSUE TITLE
About the EventInterface

### ISSUE THREAD

**Issue by nyamsprod** [benplummer/calendarful#1]
Hi,

First let me say that your package looks great. But with greatnes comes remarks. I hope you'll take mine as constructive :+1: 

When you think about it, what is a Calendar event ? It's something "unique" that occurs between 2 specific timepoints. When you modify at least one of these timepoints or the Event ID, you change the event as a whole. Basically a calendar event is a TimeRange immutable value object with a unique ID. So IMHO, the simplest event interface should be written as below:
```php
interface Event
{
	public function getId();

	public function getTimeRange(); //returns a Time Range Immutable Value Object
}
```
Now to be completely honest, I'm the author of such package, [League\Period\Period](http://period.thephpleague.com), so you may think that I'm trying to push my code into your package. But that's not the intent. I like your code and I want it to focus on what it does best creating recurring events and not "wasting your time" in time range manipulation. Your package needs a real TimeRange class to greatly simplify its code. 

You would then end up with two Interfaces but with clear functionalities. All calendar events do not need to be recurrent **but** recurrent events must be calendar events.

```php
interface RecurrentEvent extends Event
{
	public function getParentId();
	public function getRecurrenceType();
	public function setRecurrenceType($type = null);
	public function getRecurrenceUntil();
	public function getOccurrenceDate();
}
```
What do you think ?

**Comment by xploSEoF** [comment]
Awesome first feedback! good seeing someone look into details.

It's a little bit of a shame this wasn't raised as two separate points so they can be discussed separately, so I'll try to discuss them here.

Ben, you've done a great job of making heavy use of the built in PHP objects and keeping this as a stand-alone project to solve a single problem.

On that note, any additions should be careful to adhere to the same principal.

The first point here is one about duration. As per usual with two related bits of data - there is a third value - the difference between. Another example is Net and Gross prices, with the VAT being the third value.

By forcing an accessor for the third value, you actually open up the possibility for the event to be stored in a different way.

Typically, we've stored the start and end date, but it's sometimes sensible to store the start time and duration - this handles a change of date better, and storage systems can better handle validity of the two bits of data (end date cannot be before start date, achieved through duration being a positive integer).

Unfortunately, this adds a little complexity - you can have an incorrect duration that doesn't match the start date and end date.

This is where some validation logic inside the interface would make sense. Realistically, there should be some anyway, just to check the dates aren't invalid.

The second point actually makes this a little easier - separate the concerns, making it easier for others to apply later on. I'll comment more on this and your questions later, as for now, I'm only part way through reading the code.

**Comment by nyamsprod** [comment]
@xploSEoF That's why I recommended @benplummer to use a package like Period or any other package which tackles the issue your are raising. 
For instance, a Period object has multiple [named constructors](http://period.thephpleague.com/api/instantiation/) that covers your first worries.

**Comment by xploSEoF** [comment]
@nyamsprod - Maybe I've missed something here, but I see this package as an extensible package, and Period is quite clearly an implementation of such a package. To include an implementation inside an extensible package is a little backwards, and, if anything, Period could implement this package...

**Comment by nyamsprod** [comment]
@xploSEoF Period just does what is says.. it deals with Time Range nothing more, nothing less. 

On the other hand a calendar to work correctly needs more logic so I would think the other way around. A calendar from the point of view of time is indeed a collection of time range object contained in another time range object. :8ball: 

The calendar specificity is that all these Time Range objects are related according to their ending timepoints and/or interval. So the basic block is a time range object, you supercharged with other properties (<- the event), from which you create a calendar. 

Not sure if I'm making myself clear :)

**Comment by benplummer** [comment]
The package now abides by the Interface Segregation principle by separating the EventInterface introducing the additional RecurrentEventInterface. I've added an extra method on the EventRegistryInterface to allow retrieval of the different types.

In regards to the Period package, I may look into integrating it for a later release as I believe some thought needs to go into the implementation.

Thanks for the feedback @nyamsprod :)
