### ISSUE TITLE
Database Architecture

### ISSUE THREAD

**Issue by KarlBaumann** [benplummer/calendarful#10]
Hi!

Thanks for the great library!

What is the recommended database setup?
Do you maybe have something like migration scripts and db seeders?

**Comment by benplummer** [comment]
Hi Karl,

Thanks - I'm glad it could be useful.

In all honesty, it's been quite a while since I worked on this sort of problem area so I'm not 100% certain if I still have any database resources on it. It's possible I do have a database dump backed up somewhere so I'll have a look for it. If I can't find that, I'll try and refresh on the structure and let you know.

**Comment by benplummer** [comment]
@KarlBaumann Apologies for the delay. I found an old database - you can run these queries to create the tables and populate them with some example records:

```
BEGIN TRANSACTION;
CREATE TABLE "recurrent_events" ("id" integer not null primary key autoincrement, "start_date" datetime not null, "end_date" datetime not null, "parent_id" integer null, "occurrence_date" datetime null, "recurrence_type" varchar null, "recurrence_until" datetime null, "created_at" datetime not null, "updated_at" datetime not null;
INSERT INTO `recurrent_events` (id,start_date,end_date,parent_id,occurrence_date,recurrence_type,recurrence_until,created_at,updated_at) VALUES (1,'2018-01-16 22:00:00','2018-01-17 03:00:00',NULL,NULL,'monthly','2021-01-17 03:00:00','2018-01-16 20:24:21','2018-01-16 20:24:21');
CREATE TABLE "events" ("id" integer not null primary key autoincrement, "start_date" datetime not null, "end_date" datetime not null, "parent_id" integer null, "occurrence_date" datetime null, "created_at" datetime not null, "updated_at" datetime not null;
INSERT INTO `events` (id,start_date,end_date,parent_id,occurrence_date,created_at,updated_at) VALUES (2,'2018-02-15 22:00:00','2018-02-16 03:00:00',1,'2018-02-16 22:00:00','2018-01-16 22:00:00','2018-01-16 22:00:00');
COMMIT;
```

The logic is a bit foggy but I believe it is this:

- An event that is recurring is added to the `recurrent_events` table. The `start_date` and `end_date` of that event are for one occurrence of it and not for the period it should recur. The `recurrence_type` and `recurrence_until` fields determine how the event recurs, as seen in the example record.

- The `events` table comes into play for 2 scenarios. First, creating a standard event that is not related to a recurrent event at all and does not recur itself. Second is the scenario related to a recurrent event. You may want to change the details or override something for an occurrence of a recurrent event in the `recurrent_events` table. When you do this, probably in the admin area of some events CMS type system, the details of the recurrent event in the `recurrent_events` table are copied to the `events` table with a couple of differences. Those differences being the actual changes you desired to the original recurrent event occurrence e.g. a date or time change, and entries for the `parent_id` and `occurrence_date` fields. The `parent_id` field indicates which recurrent event the overriding event is linked to and the `occurrence_date` specifies which occurrence of the recurrent event we want to override (the occurrence date is required as occurrences of recurrent events are generated and not stored in the database).

These fields are only the bare minimum you need. You can add any fields you want to the events and make them overridable. I believe it's also possible to also make overriding events recurrent themselves.

Hope this helps!
