### ISSUE TITLE
Recommend using Carbon

### ISSUE THREAD

**Issue by shadowhand** [benplummer/calendarful#3]
There is a really fantastic package called [Carbon](https://github.com/briannesbitt/Carbon) that could be used to make a lot of the interval and comparison code easier to understand.

For example, this code:

```php
// existing
list(, $dailyEventTime) = explode(' ', $dailyEvent->getStartDate());
...
$newStartDate = new \DateTime($date->format('Y-m-d').' '.$dailyEventTime);

// becomes
$hour = $dailyEvent->hour;
$minute = $dailyEvent->minute;
$second = $dailyEvent->second;
...
$newStartDate = $date->setTime($hour, $minute, $second);
```

Carbon can also be used for [intervals](http://carbon.nesbot.com/docs/#api-interval), so all of your recurrence loops will be simplified as well.

**Comment by benplummer** [comment]
I can definitely see the multiple benefits of using Carbon but I think this will be a task for a later release.
