### ISSUE TITLE
Weekly.php throwing exception for $startMarker->modify('P1D');

### ISSUE THREAD

**Issue by mhaynesjr** [benplummer/calendarful#8]
I am not entirely sure the cause of this, but an odd problem showed up when I ran the following line:

```
$recurrenceFactory->addRecurrenceType('weekly', 'Plummer\Calendarful\Recurrence\Type\Weekly');
$calendar = Calendarful::create($recurrenceFactory)->populate($eventRegistry, new DateTime('first day of this month'),new DateTime('last day of this month'));
```

When the code in the Weekly.php line 75 is run I get an error of:
DateTime::modify(): Failed to parse time string (P1D) at position 1 (1): Unexpected character

If I change the code to 
```
while ($startMarker->format('w') != $day) {
	$startMarker->modify('+1 day'); // <-- was 'P1D'
}
```

it works fine. I am still rather new to PHP so I am not exactly sure whats going on, but Im guessing its a PHP bug, but thought I'd pass this along if it was of any help.

**Comment by benplummer** [comment]
Thanks for letting me know :)

Could I just ask what version of PHP you are using please?

I'll take a look into this.

**Comment by mhaynesjr** [comment]
Sure. Im using PHP 5.6.15. Its a Homestead VM ( Im developing a project using the Laravel Framework ).

**Comment by benplummer** [comment]
Thanks, I'll take a look into this and keep you updated.

**Comment by mhaynesjr** [comment]
Thanks a lot. This is a great project, by the way. It is very useful in my current project. Thanks for creating and sharing it.

**Comment by benplummer** [comment]
That's no problem, I'm glad to hear it's coming in useful!

I've pushed up the fix. It was a bug in the code irrelevant to the PHP version so thanks for letting me know.

If you run `composer update` you it should include the fix now. Let me know if there's anything else I can help with.
